pipeline {
    agent any

      triggers {
    githubPush()
  }



tools {nodejs "Node"}


      environment {
        SCANNER_HOME=tool 'sonarqube-scanner'
    }
    
    stages{
        
        stage("scm"){
            
            steps {
                
               build job: "acme", wait: true
            }
        }

                stage("test"){
            
            steps {
                
               build job: "acme-tests", wait: true
            }
        }
     
                stage("hello"){
            
            steps {
                
                echo "hello world"
            }
        }

                        stage("sonar"){
            
            steps {
                
                withSonarQubeEnv('sonarqube-scanner') {
                    sh ''' $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=test \
                    -Dsonar.java.binaries=. \
                    -Dsonar.projectKey=test '''
}
            }
        }

                                stage("deploy"){
            
            steps {
                sh'cURL -X GET https://api.render.com/deploy/srv-ci9dsf18g3ne2eie5ai0?key=CXp3Ik7H4r4'

            }
        }


    }
}