pipeline {
    agent any
      triggers {
    githubPush()
  }
tools {nodejs "Node"}
    
    stages{
        
        stage("scm"){
            
            steps {
                
               build job: "acme", wait: true
            }
        }

                stage("test"){
            
            steps {
                
               build job: "acme-tests", wait: true
            }
        }
     
                stage("hello"){
            
            steps {
                
                echo "hello world"
            }
        }


    }
}