pipeline {
    agent any

    environment {
        SCANNER_HOME=tool 'sonar-scanner'
    }

      triggers {
    githubPush()
  }
tools {nodejs "Node"}
    
    stages{
        
        stage("scm"){
            
            steps {
                
               build job: "acme", wait: true
            }
        }

                stage("test"){
            
            steps {
                
               build job: "acme-tests", wait: true
            }
        }
     
                stage("hello"){
            
            steps {
                
                echo "hello world"
            }
        }

                        stage("sonar"){
            
            steps {
                
                withSonarQubeEnv('sonar-server') {
                    sh ''' $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=test \
                    -Dsonar.java.binaries=. \
                    -Dsonar.projectKey=test '''
}
            }
        }


    }
}